---
name: WWW-LimerickDB
version: 0.0303
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: interface to fetch limericks from http://limerickdb.com/
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Data::Accessor: 0.04001
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 2.036
  overload: 1.04
build_requires:
  Test::More: 0
provides:
  WWW::LimerickDB:
    file: lib/WWW/LimerickDB.pm
    version: 0.0303
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
